app:
    image: dockerrepo.eionet.europa.eu:5000/webq2
    environment:
        - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom -Ddb.driver=com.mysql.cj.jdbc.Driver -Ddb.url=jdbc:mysql://webqdb/webq2?maxAllowedPacket=32212254720 -Ddb.username=itests -Ddb.password=password -Dcas.service=http://localhost:8080/ -Dinitial.admin.username=roug
        - JAVA_OPTS=-Xmx3072m
    ports:
        - "8080:8080"
    links:
        - webqdb:webqdb

webqdb:
    image: mysql:5.5
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=webq2
        - MYSQL_USER=itests
        - MYSQL_PASSWORD=password
    command: mysqld --max_allowed_packet=30M
    volumes_from:
        - data_db


data_db:
    image: tianon/true
    volumes:
        - /var/lib/mysql
