/*
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is Web Questionnaires 2
 *
 * The Initial Owner of the Original Code is European Environment
 * Agency. Portions created by TripleDev are Copyright
 * (C) European Environment Agency.  All Rights Reserved.
 *
 * Contributor(s):
 *        Enriko Käsper
 */
package eionet.webq.web.controller;

import eionet.webq.dto.UploadForm;
import eionet.webq.dto.UserFile;
import eionet.webq.dto.XmlSaveResult;
import eionet.webq.service.ConversionService;
import eionet.webq.service.UserFileService;
import org.apache.commons.io.IOUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.io.InputStream;
import java.util.Collection;

/**
 * Base controller for front page actions.
 *
 * @author Enriko Käsper
 */
@Controller
@RequestMapping("/")
public class BaseController {
    /**
     * Service for user uploaded files.
     */
    @Autowired
    private UserFileService userFileService;
    /**
     * File conversion service.
     */
    @Autowired
    private ConversionService conversionService;

    /**
     * Action to be performed on http GET method and path '/'.
     *
     * @param model holder for model attributes
     * @return view name
     */
    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String welcome(Model model) {
        model.addAttribute("uploadedFiles", allFilesWithConversions());
        String uploadForm = "uploadForm";
        if (!model.containsAttribute(uploadForm)) {
            model.addAttribute(uploadForm, new UploadForm());
        }
        return "index";
    }

    /**
     * Upload action.
     *
     * @param uploadForm represents form used in UI, {@link UploadForm#userFile} will be converted from
     *            {@link org.springframework.web.multipart.MultipartFile}
     * @param result binding result, contains validation errors
     * @param model holder for model attributes
     * @return view name
     */
    @RequestMapping(value = "uploadXml", method = RequestMethod.POST)
    public String upload(@Valid @ModelAttribute UploadForm uploadForm, BindingResult result, Model model) {
        if (!result.hasErrors()) {
            UserFile file = uploadForm.getUserFile();
            userFileService.save(file);
            model.addAttribute("message", "File '" + file.getName() + "' uploaded successfully");
        }
        return welcome(model);
    }

    /**
     * Removes selected user files
     *
     * @param selectedUserFile ids of files to be removed
     * @param model holder for model attributes
     * @return view name
     */
    @RequestMapping(value = "/remove/files")
    public String removeUserFiles(@RequestParam int[] selectedUserFile, Model model) {
        userFileService.removeFilesById(selectedUserFile);
        model.addAttribute("message", "Selected files removed successfully");
        return welcome(model);
    }


    /**
     * Update file content action. The action is called from XForms and it returns XML formatted result.
     *
     * @param fileId file id to update
     * @param request current request
     * @return response as application/xml generated by {@link org.springframework.oxm.jaxb.Jaxb2Marshaller}
     */
    @RequestMapping(value = "/saveXml", method = RequestMethod.POST)
    @ResponseBody
    public XmlSaveResult saveXml(@RequestParam int fileId, HttpServletRequest request) {
        UserFile file = new UserFile();
        XmlSaveResult saveResult = null;
        InputStream input = null;
        try {
            input = request.getInputStream();
            byte[] fileContent = IOUtils.toByteArray(input);
            file.setContent(fileContent);
            file.setSizeInBytes(fileContent.length);
            file.setId(fileId);
            userFileService.updateContent(file);
            saveResult = XmlSaveResult.valueOfSuccess();
        } catch (Exception e) {
            saveResult = XmlSaveResult.valueOfError(e.toString());
        } finally {
            IOUtils.closeQuietly(input);
        }
        return saveResult;
    }

    /**
     * Open selected webform. The action stores an empty XML file in user XML files area.
     *
     * @param form webform path to open
     * @param request current request
     * @return redirection URL of webform with correct parameters
     */
    @RequestMapping(value = "/startWebform")
    public String saveXml(@RequestParam String form, HttpServletRequest request) {
        UserFile file = new UserFile();
        // FIXME read the following properties from project file storage
        file.setName("new.xml");
        file.setXmlSchema("http://biodiversity.eionet.europa.eu/schemas/bernconvention/derogations.xsd");
        // TODO load XML content from the project_file.empty_instance_url field, if exists.

        int fileId = userFileService.save(file);

        return "redirect:" + form + "?fileId=" + fileId + "&base_uri=" + request.getContextPath();
    }

    /**
     * Loads and sets conversions for files uploaded by user.
     *
     * @return all uploaded files with available conversions set.
     */
    private Collection<UserFile> allFilesWithConversions() {
        Collection<UserFile> userFiles = userFileService.allUploadedFiles();
        for (UserFile userFile : userFiles) {
            userFile.setAvailableConversions(conversionService.conversionsFor(userFile.getXmlSchema()));
        }
        return userFiles;
    }
}
